/*
  libchessmove.h - Valid chess move library for cc65

  2023-07-14 - 2023-07-14
*/

/* White pieces have a high nybble of 0.
   Black pieces have a high nybble of 1. */
#define CHESSPIECE_BLACK 0x00
#define CHESSPIECE_WHITE 0x10

#define CHESSPIECE_PAWN   0x1
#define CHESSPIECE_ROOK   0x2
#define CHESSPIECE_KNIGHT 0x3
#define CHESSPIECE_BISHOP 0x4
#define CHESSPIECE_QUEEN  0x5
#define CHESSPIECE_KING   0x6

#define CHESSPIECE_EMPTY        0x00
#define CHESSPIECE_PAWN_WHITE   (CHESSPIECE_WHITE | CHESSPIECE_PAWN)
#define CHESSPIECE_PAWN_BLACK   (CHESSPIECE_BLACK | CHESSPIECE_PAWN)
#define CHESSPIECE_ROOK_WHITE   (CHESSPIECE_WHITE | CHESSPIECE_ROOK)
#define CHESSPIECE_ROOK_BLACK   (CHESSPIECE_BLACK | CHESSPIECE_ROOK)
#define CHESSPIECE_KNIGHT_WHITE (CHESSPIECE_WHITE | CHESSPIECE_KNIGHT)
#define CHESSPIECE_KNIGHT_BLACK (CHESSPIECE_BLACK | CHESSPIECE_KNIGHT)
#define CHESSPIECE_BISHOP_WHITE (CHESSPIECE_WHITE | CHESSPIECE_BISHOP)
#define CHESSPIECE_BISHOP_BLACK (CHESSPIECE_BLACK | CHESSPIECE_BISHOP)
#define CHESSPIECE_QUEEN_WHITE  (CHESSPIECE_WHITE | CHESSPIECE_QUEEN)
#define CHESSPIECE_QUEEN_BLACK  (CHESSPIECE_BLACK | CHESSPIECE_QUEEN)
#define CHESSPIECE_KING_WHITE   (CHESSPIECE_WHITE | CHESSPIECE_KING)
#define CHESSPIECE_KING_BLACK   (CHESSPIECE_BLACK | CHESSPIECE_KING)

#define piece_color(x) (x & 0xF0)

enum {
  CHESSMOVE_INVALID,
  CHESSMOVE_VALID,
  CHESSMOVE_ERROR,
};

typedef unsigned char piece_t;

char valid(piece_t * board, int old_pos, int new_pos);

