# Defaults for when values are not specified on the command line
TCP_SERVER_ADDRESS = \"TMA-2\"
TCP_SERVER_PORT = \"6502\"
TNFS_FILE_PATH = \"TMA-2/TEST.DAT\"

CFLAGS += -DTCP_SERVER_ADDRESS=$(TCP_SERVER_ADDRESS) -DTCP_SERVER_PORT=$(TCP_SERVER_PORT) -DTNFS_FILE_PATH=$(TNFS_FILE_PATH)
ASFLAGS += -DTCP_SERVER_ADDRESS=$(TCP_SERVER_ADDRESS) -DTCP_SERVER_PORT=$(TCP_SERVER_PORT) -DTNFS_FILE_PATH=$(TNFS_FILE_PATH)
LDFLAGS += -DTCP_SERVER_ADDRESS=$(TCP_SERVER_ADDRESS) -DTCP_SERVER_PORT=$(TCP_SERVER_PORT) -DTNFS_FILE_PATH=$(TNFS_FILE_PATH)