CURRENT_PLATFORM_apple2 := apple2
CURRENT_PLATFORM_apple2enh := apple2
CURRENT_PLATFORM_atari := atari
CURRENT_PLATFORM_atarixl := atari

#CURRENT_PLATFORM_c64 := apple2
#CURRENT_PLATFORM_c128 := apple2

CURRENT_PLATFORM = $(CURRENT_PLATFORM_$(CURRENT_TARGET))
