##
## Capture the Flag Makefile
##

.PHONY: all clean

all: ctf-fujinet.xex

ndev.com:
	mads src/ndev.s -l:ctf-fujinet.lst -o:ctf-fujinet.com

clean:
	rm -rf ctf-fujinet.com ctf-fujinet.lst


