##
## Capture the Flag Makefile
##

.PHONY: all clean

all: ctf-fujinet.xex

ctf-fujinet.xex:
	mads src/ctf.asm -l:ctf-fujinet.lst -o:ctf-fujinet.xex

clean:
	rm -rf ctf-fujinet.xex ctf-fujinet.lst


